---
- name: Create pods using deployment and expose the service for the application
  hosts: localhost
  become: yes
  become_method: sudo
  
  collections:
  - community.kubernetes
  
  tasks: 
  - name: create a deployment
    shell: |
      /home/ansadmin/bin/kubectl --kubeconfig=/home/ansadmin/.kube/config apply -f /opt/k8s-ansible/kubernetes/deployment.yaml
    
  - name: create a service
    shell: |
      /home/ansadmin/bin/kubectl --kubeconfig=/home/ansadmin/.kube/config apply -f /opt/k8s-ansible/kubernetes/service.yaml
